[package]
name = "{{project_name}}-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
{{project_name}}-core = { path = "../core" }
anyhow.workspace = true
serde.workspace = true
tokio.workspace = true
{{persistence_deps}}
